### ISSUE TITLE
it works, but can't see new msgs from anyone, server or dm's

### ISSUE THREAD

**Issue by ftk789** [soullessremedy/discord-cordless#1]
![image](https://user-images.githubusercontent.com/57598907/126870207-e2a743be-3ad8-4968-8bf2-954c020e263e.png)

**Comment by ftk789** [comment]
cannot see any newer msgs

**Comment by soullessremedy** [comment]
yeah, because this is fork of the original cordless.
discord keeps updating and completely broke function for receiving messages

сб, 24 июл. 2021 г. в 18:41, ftk789 ***@***.***>:

**Comment by ftk789** [comment]
so no fix? aww man, thank u anyway man <3

**Comment by soullessremedy** [comment]
no problem dude!
i'll try to look into the new ways of, like, rebuilding cordless from the
deep-down when i'll have some free time

see ya!


ср, 28 июл. 2021 г. в 23:44, ftk789 ***@***.***>:

**Comment by ftk789** [comment]
much love <3
